spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:27018/order_service
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 9002
inventory:
  url: http://localhost:9003