spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://localhost:27019/inventory_service
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 9003